<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditProducts.aspx.cs" MasterPageFile="~/AdminPortal/adminmaster/AdminPortalMaster.Master" Inherits="XEHAR2017.AdminPortal.AdminPortalViews.EditProducts" EnableEventValidation="false" EnableViewState="true" MaintainScrollPositionOnPostback="true" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">All Products</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                                <div class="row">
                                    <div class="col-sm-6"></div>
                                    <div class="col-sm-6"></div>

                                </div>
                                <div class="row" style="height:800px; width:auto; overflow:auto;">
        
                                    <div class="col-sm-12">
                                        <asp:GridView ID="gv1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"   OnRowEditing="Gv1_RowEditing" OnRowCancelingEdit="Gv1_CancelingEdit" OnRowUpdating="Gv1_RowUpdating" OnRowDeleting="Gv1_RowDelete"   ForeColor="#333333" MaintainScrollPositionOnPostback="true" Width="100%">
                                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333"  />
                                            <Columns>
                                                <asp:CommandField ShowEditButton="True" />
                                                <asp:BoundField DataField="cname" HeaderText="SKU" InsertVisible="False" ReadOnly="True" SortExpression="SKU" />
                                                <asp:BoundField   DataField="ppid" HeaderText="ppid" SortExpression="ppid" InsertVisible="False" ReadOnly="True" />
                                                 <asp:BoundField  DataField="cid" HeaderText="cid" SortExpression="cid" InsertVisible="False" ReadOnly="True" />
                                                <asp:BoundField   DataField="csize" HeaderText="csize" SortExpression="csize" InsertVisible="False" ReadOnly="True" />
                                                <asp:BoundField   DataField="ccparentid" HeaderText="ccparentid" SortExpression="ccparentid" InsertVisible="False" ReadOnly="True"/>
                                                <asp:BoundField   DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                                                <asp:BoundField   DataField="xehar_desc" HeaderText="Description" SortExpression="Description" ControlStyle-BorderWidth="100px" />
                                                <asp:BoundField   DataField="CountryOrigin" HeaderText="Country" SortExpression="Country" />
                                                <asp:BoundField   DataField="sname" HeaderText="Size" SortExpression="Size" />
                                                <asp:BoundField   DataField="cquant" HeaderText="Quantity" SortExpression="Quantity" />
                                                <asp:BoundField   DataField="Front" HeaderText="Front Image" SortExpression="Front" />
                                                <asp:BoundField   DataField="Back" HeaderText="Back Image" SortExpression="Back" />
                                                <asp:BoundField   DataField="Left" HeaderText="Left Image" SortExpression="Left" />
                                                <asp:BoundField   DataField="Right" HeaderText="Right Image" SortExpression="Right" />
                                                <asp:BoundField   DataField="extra1" HeaderText="Extra Image" SortExpression="extra1" />
                                                <asp:BoundField   DataField="extra2" HeaderText="Extra Image" SortExpression="extra2" />
                                                <asp:BoundField   DataField="ExtraFeatures" HeaderText="Features" SortExpression="Features" />
                                                <%--<asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" InsertVisible="False" ReadOnly="True" />--%>
                                                <%--<asp:TemplateField HeaderText="ProductName"  SortExpression="ProductName">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox" runat="server"  Text='<%# DataBinder.Eval(Container, "DataItem.ProductName") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.ProductName") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox" runat="server" Text='<%#DataBinder.Eval(Container, "DataItem.ProductName") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>--%>
                                                <%--<asp:TemplateField HeaderText="Description" SortExpression="Description">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox2" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.xehar_desc") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label2" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.xehar_desc") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox2" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.xehar_desc") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Country" SortExpression="Country">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox1" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.CountryOrigin") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label1" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.CountryOrigin") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox1" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.CountryOrigin") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Size" SortExpression="Size">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox3" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.sname") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label3" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.sname") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox3" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.sname") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Quantity" SortExpression="Quantity">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox6" runat="server" Visible='<%# IsInEditMode %>' Text='<%#  DataBinder.Eval(Container, "DataItem.cquant") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label6" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%#  DataBinder.Eval(Container, "DataItem.cquant") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox6" runat="server" Visible='<%# IsInEditMode %>' Text='<%#  DataBinder.Eval(Container, "DataItem.cquant") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                    <ItemStyle HorizontalAlign="Center" />
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Image1" SortExpression="Image1">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox4" runat="server" Visible='<%# IsInEditMode %>' Text='<%#  DataBinder.Eval(Container, "DataItem.Front") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label4" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%#  DataBinder.Eval(Container, "DataItem.Front") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox4" runat="server" Visible='<%# IsInEditMode %>' Text='<%#  DataBinder.Eval(Container, "DataItem.Front") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Image2" SortExpression="Image2">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox5" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.Back") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label5" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.Back") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox5" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.Back") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Image3" SortExpression="Image3">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox7" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.Left") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label7" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.Left") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox7" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.Left") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Image4" SortExpression="Image4">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox8" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.Right") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label8" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.Right") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox8" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.Right") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Image5" SortExpression="Image5">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox9" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.extra1") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label9" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.extra1") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox9" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.extra1") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Image6" SortExpression="Image6">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox11" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.extra2") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label11" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.extra2") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox11" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.extra2") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Features" SortExpression="Features">
                                                    <EditItemTemplate>
                                                        <asp:TextBox ID="TextBox12" runat="server" Visible='<%# IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.ExtraFeatures") %>'></asp:TextBox>
                                                    </EditItemTemplate>
                                                    <ItemTemplate>
                                                        <asp:Label ID="Label12" runat="server" Visible='<%# !(bool) IsInEditMode %>' Text='<%# DataBinder.Eval(Container, "DataItem.ExtraFeatures") %>'></asp:Label>
                                                        <asp:TextBox ID="TextBox12" runat="server" Visible='<%# IsInEditMode %>' Text='<%#DataBinder.Eval(Container, "DataItem.ExtraFeatures") %>'></asp:TextBox>
                                                    </ItemTemplate>
                                                </asp:TemplateField>--%>
                                            </Columns>
                                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                            <EditRowStyle BackColor="#999999" />
                                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                        </asp:GridView>
                                    </div>
                                </div>

                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                        <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->


            </div>
        </section>
    </div>
</asp:Content>

